In [3]:
import numpy as np
# a = numpy.array(                [
#                     [[[0.4, 0.05], [2.95, 1.3]], [[4.8, 1.2], [1.65, 3.1]]],
#                     [[[1.45, 3.05], [2.25, 0.1]], [[0.45, 4.75], [1.5, 1.8]]],
#                     [[[1.5, 4.65], [1.35, 2.7]], [[2.0, 1.65], [2.05, 1.2]]],
#                 ])
# print(a.shape)
# print(a)
# b = numpy.transpose(a)
# print(b.shape)
# print(b)
# c = numpy.array([
#                     [[[0.4, 2.95], [0.05, 1.3]], [[4.8, 1.65], [1.2, 3.1]]],
#                     [[[1.45, 2.25], [3.05, 0.1]], [[0.45, 1.5], [4.75, 1.8]]],
#                     [[[1.5, 1.35], [4.65, 2.7]], [[2.0, 2.05], [1.65, 1.2]]],
#                 ])
# print(c.shape)
# print(c)




a = np.random.rand(2, 2)
print(a)
a/10
print(a)
np.divide(a, 10)
print(a)

[[0.59666267 0.77079334]
 [0.23665379 0.86783808]]
[[0.59666267 0.77079334]
 [0.23665379 0.86783808]]
[[0.59666267 0.77079334]
 [0.23665379 0.86783808]]
